### PR TITLE
[Fixes #9, #16, partial #19] Override wordWrap method to ignore tags

### LINKED ISSUE #9: Fix breakWords property
Currently, using `breakWords` to allow line breaks caused by word wrapping to occur mid-word causes tags to be broken.  Obviously, the width of the tags shouldn't be included in the width of the text.

Fixing this would probably require overriding `PIXI.Text`'s `wordWrap` method to not count the tags when computing widths.

### PR DESCRIPTION
**Pull request by bluepichu**
This should fix all of the wrapping related issues we have open.  Centering isn't fixed here, though, so this isn't a full fix for #19.

No breaking changes, only bugfixes.

### CODE REVIEW

**Comment by bluepichu** [comment]
Actually, I think the centering issue mentioned in #19 is a different one than the one I'm seeing.  I'll open a new issue for what I've found.

**Comment by tleunen** [comment]
I wonder, can't we just use the parent `wordWrap` instead of duplicating the code?
What if we remove the tags, send it to the parent `wordWrap` and then put back the tags?

**Comment by bluepichu** [comment]
I considered that, but I couldn't find a good way considering that we need to change the style every time we reach a tag, and the `wordWrap` method from `Text` assumes that the text is only one style, so the widths are computed incorrectly if a tag changes any of the font properties to a value other than what is in the `default` style.

**Comment by bluepichu** [comment]
Regarding the centering issue: what I was seeing was that text is centered relative to the maximum text width (not the `wordWrapWidth`) even when `wordWrap` was enabled, which seemed kind of strange.  However, this behavior (as well as some other strange word-wrap-related behaviors) are consistent with `PIXI.Text`, so I won't consider them issues unless `PIXI.Text`'s behavior changes.

**Comment by tleunen** [comment]
Oh you're right, the style of the text might cause it to wrap too.

**Pull request merged**
