### PR TITLE
Tests (Happo edition)

### PR DESCRIPTION
**Pull request by bluepichu**
This is looking a lot better!  However, we seem to be running into Galooshi/happo#132 since I'm using Chrome.

### CODE REVIEW

**Comment by bluepichu** [comment]
One method of fixing this is to not set `PIXI.settings.RESOLUTION = 2`, at the cost of blurry text.

Another is to make the canvas twice as big (on both dimensions) as it needs to be, so when the snapshot cuts it down, you still get the important bits.

While it's a bit hackier, I'll stick with the second one for now.

**Comment by bluepichu** [comment]
As far as I know, Happo looks on your `PATH`, so we could set up the script to add the path to a local installation of `chromedriver` for the duration of the command.

You should already have write access to the branch - the box was already checked.  And please feel free to set up the CI stuff :)

**Comment by tleunen** [comment]
Still working on that, I'll let you know when it's ready ;)

**Comment by bluepichu** [comment]
I did a quick rebase to bring this branch up-to-date.

**Comment by bluepichu** [comment]
Rebased again to fix some `package.json` conflicts.

**Comment by bluepichu** [comment]
It also looks like we'll need to have our CI script install Pixi in addition to PMT, since Pixi is now a peer dependency (and those aren't installed with `npm install`).

**Comment by tleunen** [comment]
In that case, we should also add it in the dev dependencies so it will be installed for the tests.

I'll give this a shot again when I get some time, maybe this weekend.

Thanks again for all you do in this project!

**Comment by bluepichu** [comment]
Anything I can do to help with this?  I might have a bit of time this weekend and in the middle of next week.

**Comment by tleunen** [comment]
You should have access to circle-ci, right?
So I wanted to try running happo there, then using argos-ci to compare the screenshots.
https://www.argos-ci.com It's new, but it seems to work fine.

It's used for this project https://github.com/algolia/react-instantsearch

**Comment by bluepichu** [comment]
Getting close - for some reason the Argos token environment variable isn't working on CircleCI (the passed check above was me doing a manual upload).

**Comment by bluepichu** [comment]
Ok - the problem seems to be that circleci won't give the Argos secret to a fork, which makes sense.  I'm not sure what to do about it though.

**Comment by tleunen** [comment]
Hmm.. What do you mean exactly? All env variables should be used to build PR as well

**Comment by bluepichu** [comment]
CircleCI suppresses giving environment variables with tokens/secrets to forks, because someone could theoretically create a fork that sends the secrets to an external location to steal them.

**Comment by bluepichu** [comment]
I've enabled builds of fork PRs.  A malicious PR could feasibly steal the Argos key, but that should be the only useful information they can take.  (There should also be an SSH key on there that CircleCI uses to pull from this repo, but assuming the permissions are set appropriately on that, it would just allow read access on a public repo.)  The upside of this method to anything else I could come up with is that an attacker would need to file a PR, so we'd know that it's happening.

Let me know if we need to disable this for some reason.

**Comment by bluepichu** [comment]
Merging so that we can make sure that Argos's diff is working.

**Pull request merged**
