### PR TITLE
CI: Happo fixes

### PR DESCRIPTION
**Pull request by bluepichu**
Since I'm less convinced this will work right away, I want to make sure Happo runs cleanly on Circle before merging to master.  If this builds, I'll merge so that I can make sure Argos does the diff cleanly.

### CODE REVIEW

**Comment by bluepichu** [comment]
Hmmm... so the filenames are better, but the output images are still wrong...

**Comment by tleunen** [comment]
What do you mean by the output is wrong?

**Comment by bluepichu** [comment]
[See here.](https://www.argos-ci.com/tleunen/pixi-multistyle-text/builds/10859)  "Basic example" doesn't receive an image at all; "Break words" receives the image that should go with "Have fun"; "Have fun" receives the image that should go with "Wrapping and alignment"; etc.

This issue appears to be on the CircleCI side, since I observe the same incorrect results when I just `scp` the `happo-snapshots` directory after a CircleCI run.  However, I get the correct output when I run `npm run happo` locally.

**Comment by tleunen** [comment]
Hmm this is strange, indeed.

Btw, Don't know if you saw the news about it. https://happo.io/
https://medium.com/happo-io/introducing-happo-io-45de5e6592b6

**Pull request closed without merging**
