### PR TITLE
Tests (Jest edition)

### PR DESCRIPTION
**Pull request by bluepichu**
**Not ready for merge.**

I made a better demo page that has easily-accessible code samples.  I'm currently looking into solutions for taking a canvas snapshot on the first frame and using that to do automated testing.

Can you think of any other tests/examples that would be good to put here?

### CODE REVIEW

**Comment by tleunen** [comment]
For a proper tests, if 2 canvas with exactly the same thing produce exactly the same "data url", we can probably get the data URL and save its snapshot the first time the test run, and then just compare the test result with it.

Jest (the test framework) offer an easy snapshot system, so we can pass what we want to that and it will save it in another file. With the data url, we can also easily see the result by using this as a base64 string to render the image.

Another way would be to snapshot the array of pixels in the canvas.

**Comment by bluepichu** [comment]
I finally figured out how to get Jest to play nicely with Canvas and patch in everything that Pixi needs to get a test running, but the result was... underwhelming.  Not sure what to do about it yet.

## Automated Test Output (jsdom + node-canvas)

screenshot 2017-01-02 23 27 13

## Browser Output (Chrome)

screenshot 2017-01-02 23 28 58

**Comment by bluepichu** [comment]
Another failing example:

## Automated Test Output

screenshot 2017-01-02 23 55 26

## Browser Output

screenshot 2017-01-02 23 55 06

It seems that this test suite is
- measuring text incorrectly
- ignoring italics
- ignoring font weight
- not respecting resolution
- not respecting font size changes

We may need to look into using something like Karma to actually run the code in-browser rather than shimming it to run in node-canvas.

**Comment by tleunen** [comment]
Hmm.. Thanks for testing all this. Indeed, it seems testing canvas with jsdom is definitely not accurate :( 

The only other way I know of would be some sort of visual testing. We could use something like [happo](https://github.com/Galooshi/happo) instead of doing it manually with karma. What do you think?

**Comment by tleunen** [comment]
Maybe you can keep this PR to keep what you currently have with jsdom, create another PR for testing with another framework, and also create another one just for the new demos so we can already merge the new demo page? :)

**Comment by bluepichu** [comment]
Sounds like a plan.

**Comment by bluepichu** [comment]
Closing in favor of #29.

**Pull request closed without merging**
