### PR TITLE
feat: Support PIXI v5

### LINKED ISSUE #83: Do you plan to make it compatible with Pixi 5?
I'm migrating my project and wanted to know if it's planned.

### PR DESCRIPTION
**Pull request by exoego**
Closes #83 

I took over PR #79 by @motla, because I really need PIXI5 support.

### CODE REVIEW

**Comment by exoego** [comment]
@tleunen 

It seems that build succeeded, then some test fails
```
large (2048x2048) Error: Error: Error rendering "Basic example":
  WebGL unsupported in this browser, use "pixi.js-legacy" for fallback canvas2d support.
    at /root/project/node_modules/happo-target-firefox/lib/index.js:49:19
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```
in https://circleci.com/gh/tleunen/pixi-multistyle-text/86?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

Do you have any idea to resolve this?

**Comment by themoonrat** [comment]
Some test environments do not have WebGL support. 
In v4, PixiJS supported bother canvas and WebGL out of the box
For v5, regular PixiJS supports WebGL, but only the legacy builds includes Canvas support.

Should be a case of switching over unit tests to rely and use pixi-legacy.js rather than pixi.js

**Comment by exoego** [comment]
Is it OK to switch from pixi.js to pixi.js-legacy ?
Or, is it possible to use pixi.js-legacy only on test ?

**Comment by themoonrat** [comment]
The only reason it exists as a dev dependency is for the unit tests, I believe, so I think it'll be fine to switch.

**Comment by tleunen** [comment]
You probably want to update this line too https://github.com/tleunen/pixi-multistyle-text/blob/master/.happo.js#L14

**Comment by tleunen** [comment]
cc @blurymind Mind taking a look as well? I think you want to keep v4 compatibility for a bit until Gdevelop moves to v5?

We can also decide to only support v5 going forward and release a major version.

**Comment by exoego** [comment]
OK, now CI is green.

**Comment by blurymind** [comment]
Feel free to upgrade it 😁 once he moves to pixi5, we will move to the
upgraded version too

**Comment by estashuk** [comment]
Hi guys, can you please push this version to npm?

**Comment by tleunen** [comment]
I'm going to merge it and release a version.

What's going to happen to Pixi with canvas support? Are they dropping it?

**Comment by blurymind** [comment]
@4ian the pixi-multistyle library now supports pixi5, so it wont be a problem when updating GD to 5 :)

**Comment by 4ian** [comment]
Great! We should get started with the migration to Pixi 5 on GDevelop then :)

**Comment by Bouh** [comment]
Will there be support for bitmapText from pixi v5 ?

**Pull request merged**
