### PR TITLE
[Fixes #6] Port to TypeScript; Update for Pixi 4.2

### LINKED ISSUE #6: Centering multi-line text broken in pixi 4.1.1, entire library broken in pixi 4.2.3
Can't seem to get it to work at all, is it just me?

Edit: Tried updating pixi to the latest and it broke everything :P Seems like fonts changed quite a bit

>Deprecation Warning: determineFontProperties is now deprecated, please use the static calculateFontProperties method, e.g : Text.calculateFontProperties(fontStyle);

>Uncaught TypeError: Text.calculateFontProperties is not a function(…)
>determineFontProperties	@	deprecation.js:682
>MultiStyleText.updateText	@	pixi-multistyle-text.js:217
>...

Changing line 217 to this fixed the 'completely broken' issue at least:
>outputTextData[i][j].fontProperties = PIXI.Text.calculateFontProperties(outputTextData[i][j].style.font);

I'm not github savvy enough to do more than comment right now sorry

### PR DESCRIPTION
**Pull request by bluepichu**
Sorry for the delays on this - exams hit me hard last week.

This PR ports the entire library to TypeScript, which I think may help it be more maintainable.  To the user, this change has no effect since TS compiles down to plain JS.  (Unless the user is using TS; then they get the added bonus of a bundled type declaration file.)

This rewrite does introduce some breaking changes:

- The `def` style has been renamed to `default` for added clarity.
- Alignment and word wrap properties are controlled by the `default` style, rather than by a separate object passed to the constructor.  (Some related methods have been removed.)
- The default values for the various style options were updated to reflect Pixi's defaults.
- The library uses ES6's `class` syntax, which would make the library not function correctly on browsers with poor ES6 support.  (However, the library already contained `Object.assign` from my last PR, so some level of ES6-compliance was already required anyway.)

Most of the source is unchanged save the added type annotations and ES6 niceties (e.g., `let` instead of `var`), so this should be relatively safe to pull.  Pending any objection from @tleunen, I'll do that later tonight.

### CODE REVIEW

**Comment by tleunen** [comment]
I trust you for the code, but, should we compile down to ES5 just in case?
Also, the version will be set when releasing the new version, so no need to put an explicit 0.4.0.

But huge thanks for the update!

**Comment by bluepichu** [comment]
It occurred to me that retargeting for ES5 wasn't actually too hard, so I went ahead and did that.  While abandoning `class` syntax in the emitted code makes slightly it less readable, that should be fairly irrelevant given sourcemaps.

Also, reverted version bump.

**Comment by tleunen** [comment]
Great! Lets go with that and we'll iterate from there if we find issues :)

Could you also give me your username on npm? I'll add your as a collaborator so you can also release versions.

**Comment by bluepichu** [comment]
Sounds good.  I'm `bluepichu` there as well.

**Pull request merged**
