### PR TITLE
Test PR, please ignore

### PR DESCRIPTION
**Pull request by bluepichu**
Triggering CI to make sure diffing works.

### CODE REVIEW

**Comment by bluepichu** [comment]
...so CircleCI just prints the token, which is suboptimal.

Also the diff didn't work.

**Comment by bluepichu** [comment]
Hmm, looks like the screenshots aren't matching up correctly...

**Comment by bluepichu** [comment]
CircleCI/Happo seems to be generating the same screenshot under multiple names and not taking other ones at all.  (Perhaps this is a race condition of some kind?)

I'm not sure what to do about this.

**Comment by tleunen** [comment]
Yeah, actually, I think that's why they "normalize" it here https://github.com/algolia/react-instantsearch/blob/master/package.json#L25

**Pull request closed without merging**
