### PR TITLE
[Fixes #10] Fix build errors

### LINKED ISSUE #10: Cannot run `npm run build`
@bluepichu I've never really used typescript before. Could you explain what's missing for me to run `npm run build`?

I'm currently getting a lot of errors like these:
```
pixi-multistyle-text.ts(3,37): error TS2503: Cannot find namespace 'PIXI'.
pixi-multistyle-text.ts(3,37): error TS4022: Extends clause of exported interface 'ExtendedTextStyle' has or is using private name 'PIXI'.
pixi-multistyle-text.ts(36,30): error TS2304: Cannot find name 'PIXI'.
pixi-multistyle-text.ts(36,30): error TS4020: Extends clause of exported class 'MultiStyleText' has or is using private name 'PIXI'.
pixi-multistyle-text.ts(49,4): error TS2322: Type '{ align: string; breakWords: boolean; dropShadow: boolean; dropShadowAngle: number; dropShadowBlu...' is not assignable to type 'ExtendedTextStyle'.
  Object literal may only specify known properties, and 'align' does not exist in type 'ExtendedTextStyle'.
```

Also, we should add `typescript` as a dev dependency.

### PR DESCRIPTION
**Pull request by bluepichu**
This PR fixes some TS errors that were in the previous version and switches from `@types/pixi.js` to `pixi-typescript` for the Pixi typings definition files, as the latter is generally kept more up-to-date.  At some point we should hopefully be able to revert to `@types/pixi.js` or remove the dependency altogether depending on how the folks at `pixi-typescript` decide to handle definition management long-term.

### CODE REVIEW

**Comment by bluepichu** [comment]
Yikes, this isn't ready.  I didn't realize that this totally breaks the `.d.ts` output and makes it unusable.

**Comment by bluepichu** [comment]
Unfortunately, I fear there's no way to fix the `.d.ts` until Pixi 4.3.0 definitions hit DefinitelyTyped (which have failed twice already, see DefinitelyTyped/DefinitelyTyped#13505 and DefinitelyTyped/DefinitelyTyped#13515).  Thus, while this is sufficient to fix #10 and allows the package to be used client-side (e.g. via a `<script>` tag to import it), it won't be usable via TS until after DT gets updated.

**Comment by tleunen** [comment]
So are we waiting for the updated types in @DefinitelyTyped before we can fix the issue here? Or would this be ok to merge, without full TS support, and then fix it once and for all when they got it fixed on their side?

It seems this also has the fix for #11, can we move this in another PR so it's easier to follow what's needed for one fix and the other?

**Comment by bluepichu** [comment]
It's probably best to merge this as-is (assuming this correctly fixes the build errors) and fix TS support once DT gets updated.

This doesn't have the fix for #11; that's in 63b946e, which is in the `iss11` branch in my fork (which branches off of `build-bugfixes` after these commits, and thus depends on this PR).

**Comment by bluepichu** [comment]
Counterpoint: we can reject this PR and hope that DefinitelyTyped/DefinitelyTyped#13579 goes through.  It looks like it's passed their PR checks so hopefully that should get pulled in the next day or so, which should make it easier to do some cleanup before merging fixes to #10 and #11.

**Comment by clark-stevenson** [comment]
Andy managed to merge v4.3.0 now after my failed attempts!

**Comment by bluepichu** [comment]
Thanks @clark-stevenson!  Fixing the types now so we can get this merged in.

**Comment by bluepichu** [comment]
Welp, scratch that.  pixijs/pixi-typescript#133 never got merged in with the DT update so now we need to wait for that to get merged in as well.

**Comment by bluepichu** [comment]
Now blocked on DefinitelyTyped/DefinitelyTyped#13631.

**Comment by bluepichu** [comment]
I think this is finally ready!

**Pull request merged**
